#!/bin/sh

list_files=`find -name *.c | sort`

# unitary
echo "$list_files" | grep -e 'unitary\/.*\.c$' | while read code 
do
  if [ ! -f "$code.scop" ] || [ "$1" = "-a" ]
  then
    rm -f "$code.scop"
    echo "add $code"
    clan "$code" | clay | grep -v "File generated by" >"$code.scop"
  fi
done
